[package]
name = "pdg-rs"
description = "Programmatic access to the Particle Data Group's database with Rust"
version = "0.1.0"
edition = "2024"
authors = ["Nathaniel Dene Hoffman <nhoffman@wm.edu>"]
homepage = "https://github.com/denehoffman/pdg-rs"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/denehoffman/pdg-rs"
keywords = ["particle", "physics", "pdg"]
categories = ["command-line-utilities", "science"]
rust-version = "1.88.0"

[[bin]]
name = "pdg"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
comfy-table = { version = "7.2.2", features = ["custom_styling"] }
num = { version = "0.4.3", optional = true }
owo-colors = "4.3.0"
rusqlite = { version = "0.39.0", features = ["bundled", "serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"

[features]
default = ["ratio"]
num = ["dep:num"]
ratio = ["num"]

[lints.clippy]
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
format_push_string = "allow"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./docs-header.html"]
